# Generated by Django 2.0.3 on 2020-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20200628_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单权限需要选择一个可以成为菜单的权限，用于做默认展开和选中菜单', null=True, on_delete=None, related_name='parents', to='rbac.Permission', verbose_name='关联的权限'),
        ),
    ]
